# Generated by Django 3.2.3 on 2021-07-22 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pMentHa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='stimulus',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='SubDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subDimension', models.CharField(max_length=128)),
                ('dimension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pMentHa.dimension')),
            ],
        ),
        migrations.AddField(
            model_name='dimension',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pMentHa.question'),
        ),
    ]
