# Generated by Django 3.2.3 on 2021-07-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pMentHa', '0002_auto_20210722_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min',
            field=models.IntegerField(null=True),
        ),
    ]
