# Generated by Django 3.2.3 on 2021-07-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pMentHa', '0003_auto_20210723_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdimension',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pMentHa.question'),
        ),
        migrations.AddField(
            model_name='subdimension',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pMentHa.answer'),
        ),
    ]
